modLoader="javafml"
loaderVersion="[32,)"
license="Public Domain"
[[mods]]
modId="betterbiomeblend"
version="${version}"
displayName="Better Biome Blend"
authors="FionaTheMortal"
description="    This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one."

[[dependencies.betterbiomeblend]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
