modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="betterbiomeblend"
version="${version}"
displayName="Better Biome Blend"
logoFile=""
authors="FionaTheMortal"
description='    Mod for better biome color blending.'

[[dependencies.betterbiomeblend]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterbiomeblend]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
